# -*- coding: utf-8 -*-
"""day 2 of python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UeP6dYIZoqRjrNKuWYxwiGYDHcLK2kgm
"""



"""# operators

"""

a=10
b=20
print("addition",a+b)

print(a-b)

print(a*b)

print(b/a)

a=17
b=13
print(a//b)

a/b

a**b

d=7425
s=550
(d/s)

x=1024
tip=20/100
#tip given by the person is y
y=x*tip
print("total tip given is",y)

bill=int(input())
tip=20/100*bill
print(tip)

a=10
b=20
print(a>b)
print(a<b)
print(a==b)
print(a!=b)
print(a>=b)
print(a<=b)

a=True
b=False
print(a and b)
print(a or b)
print(not a)

a=10
b=a
print(b)
b+=a
print(b)
b-=a
print(b)
b*=a
print(b)
b<<=a
print(b)

a=10
b=20
c=a
print(a is not b)
print(a is c)
print(b is c)

x=10
y=15
list=[10,20,30,40,50]
if(x not in list):
   print("x is not present in given list")
else:
    print("x is present in given list ")
if(y in list ):
   print("y is  present in given list")
else:
    print("y is not present i given list")

(1,2,3)+(4,5,6)

[1,2,3]+[4,5,6]

"hello" +" " + " world"

(1,2,3) * 9

age=int(input())
if age<18:
   print("you can't vote!")
else:
    print("you can vote!")
print("done!")

x=35
if x>20:
    print("above twenty,")
if x> 30:
    print("and also above 30!")

a=int(input())
b=int(input())
if b>a:print("b is greater than a")
elif a == b:print("a and b are equal")

weight=int(input());
height=float(input());
x=weight/float(height*height);
if x<18.5:
  print("underweight")
if x>=18.5 and x<25:
   print("normal")
if x>=25 and x<30:
   print("overweight")
if x>=30:
   print("obesity")



