# -*- coding: utf-8 -*-
"""DAY 1 PYTHON.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uw3VPNQts6GsNE16SEL6mKyASiICpLxd
"""

print("hello world")

print(hello world)

print(5)

print(10%3)

print(145325436645231314533)

print('hello world|')
print('hello kgrcet')
print('welcome to python workshop')

name=input("enter your name:")
print("hello,"+name)

roll_number=input("Enter your roll_number:")
print("hello",roll_number)

print("your roll number is:")

_input="this is input variable"
print(_input)

x=10
print(x)

x="kgrcet"
print(x)

age=18
print("i am "+str(age)+"years old")



"""# age program"""

age=20
print("i am "+str(age)+"years old")

a=400
A="KGRCET"
#A WILL NOT OVERWRITE a
print(a)
print(A)

x=5
y="kgrcet"
print(x)
print(y)

x=4
x="hello"
print(x)

x="python"
y="is"
z="awesome"
print(x,y,z)

x="python "
y="is "
z="awesome "
print(x+y+z)

x=500
y="kgr"
print(x,y)

x,y=2,3
x

x=y=z=3
x

y

z



"""#swapping numbers

"""

a=10
b=20
a,b=b,a
a

b

x,y,z="orange","banana","cherry"
print(x)
print(y)
print(z)

x=y=z="orange"
print(x)
print(y)
print(z)

print(type(x))

x=int(3)
y=int(3)
z=float(3)

print(x+y)

x=True
print(x)
print(type(x))

a=5
 print(type(a))

b=5.0
print(type(b))

c=2+100j
print(type(c))

s="welcome to python workshop"
print(type(s))
print(s[7])
print(s[2])
print(s[-1])

string_one="i am studying"
string_two="kgrcet"
print(string_one,string_two)

string1="i am studying in"
string2="1st year"
print(string1,string2)



print('alice                              '*5)

a=[]
a=[1,2,3]
print(a)

b=["nani","hi","python",a]
print(b)

a=["python",3,"is","very","easy"]
print("accessing element from the list")
print(a[0])
print(a[2])
print("accessing element using negative ")

a=[1,2,3,4,5]
a[0:3]

a[-3:-1]

b=["kgr",1,2,3]
b[2:4]

nani_list=[6,2,43,7,3]
nani_list.sort()
nani_list
[2,3,6,7,43]

nani_list.append("5")
print(nani_list)

nani_list.insert(0,"nani")
print(nani_list)

nanda_list=["apple","orange","grapes"]
nanda_list.sort()
nanda_list

nanda_list.remove("apple")
print(nanda_list)

nanda_list.pop()
print(nanda_list)

nanda_list=["apple","orange","grapes"]
del nanda_list[1]
print(nanda_list)

